/*
 * generated by Xtext
 */
package eu.ddmore.mdl.mdllib;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MdlLibStandaloneSetup extends MdlLibStandaloneSetupGenerated{

	public static void doSetup() {
		new MdlLibStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

