/*
 * generated by Xtext
 */
package eu.ddmore.mdl.mdllib.ui.contentassist

import eu.ddmore.mdl.mdllib.ui.contentassist.AbstractMdlLibProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MdlLibProposalProvider extends AbstractMdlLibProposalProvider {
}
