/*
 * generated by Xtext
 */
package eu.ddmore.mdl.mdllib;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MdlLibRuntimeModule extends eu.ddmore.mdl.mdllib.AbstractMdlLibRuntimeModule {

}
