/*******************************************************************************
 * Copyright (c) 2016 Pfizer Ltd.
 *
 * This file is part of the MDL Library.
 *
 * The MDL Library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The MDL Library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with The MDL Library.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
/*
 * generated by Xtext
 */
package eu.ddmore.mdllib;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import eu.ddmore.mdllib.mdllib.MdlLibPackage;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MdlLibStandaloneSetup extends MdlLibStandaloneSetupGenerated{

	public static void doSetup() {
		new MdlLibStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

    @Override
    public void register(Injector injector) {
        if (!EPackage.Registry.INSTANCE.containsKey("http://eu.ddmore.mdllib/mdllib/MdlLib")) {
            EPackage.Registry.INSTANCE.put("http://eu.ddmore.mdllib/mdllib/MdlLib", MdlLibPackage.eINSTANCE);
        }
        super.register(injector);
    }
}

