/*
 * generated by Xtext
 */
package eu.ddmore.mdllib.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MdlLibWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MdlLibWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
