/*
 * generated by Xtext
 */
package eu.ddmore.mdllib.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MdlLibUiModule extends eu.ddmore.mdllib.ui.AbstractMdlLibUiModule {
	public MdlLibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
